version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    ports:
        - 5555:5432
    restart: on-failure
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: DripChip
        PGDATA: "/var/lib/postgresql/data/pgdata"

  webapi:
    build:
        context: ./
        dockerfile: ./Dockerfile
    ports:
        - 9004:80
    restart: on-failure
    depends_on:
        - postgresdb

  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
      - postgresdb
    environment:
      SERVER_URL: http://webapi
      STAGE: all

volumes:
    postgresdb:
    webapi: